const VIEWING_PARTIES = [
  {
    id: "vp1",
    title: "USA vs Mexico — Opening Match Watch Party",
    city: "Los Angeles",
    venue: "Downtown Sports Bar & Grill",
    date: "2026-06-11",
    time: "5:00 PM",
    spots: 80,
  },
  {
    id: "vp2",
    title: "Brazil vs Argentina — Group Stage",
    city: "Miami",
    venue: "Bayfront Fan Zone",
    date: "2026-06-18",
    time: "7:30 PM",
    spots: 120,
  },
  {
    id: "vp3",
    title: "Germany vs Spain — Knockout Round",
    city: "New York",
    venue: "Brooklyn Soccer Hall",
    date: "2026-07-02",
    time: "2:00 PM",
    spots: 60,
  },
  {
    id: "vp4",
    title: "Canada vs France — Group Stage",
    city: "Toronto",
    venue: "Maple Leaf Pub",
    date: "2026-06-22",
    time: "12:00 PM",
    spots: 45,
  },
  {
    id: "vp5",
    title: "World Cup Final Watch Party",
    city: "Los Angeles",
    venue: "Stadium Plaza",
    date: "2026-07-19",
    time: "1:00 PM",
    spots: 200,
  },
  {
    id: "vp6",
    title: "England vs Italy — Quarter Final",
    city: "Chicago",
    venue: "Windy City Sports Lounge",
    date: "2026-07-08",
    time: "3:00 PM",
    spots: 75,
  },
];

const CITIES = [...new Set(VIEWING_PARTIES.map((e) => e.city))].sort();
